# Generated by Django 3.1.1 on 2020-09-07 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imo', models.CharField(db_index=True, max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^|\\d{7}$')], verbose_name='IMO')),
                ('flag', models.CharField(blank=True, help_text='ISO 3-letter code', max_length=3)),
                ('ship_type', models.CharField(blank=True, help_text='Later refined as a dropdown', max_length=100, verbose_name='Type')),
                ('build', partial_date.fields.PartialDateField(blank=True, help_text='year-month', null=True)),
                ('mmsi', models.CharField(blank=True, db_index=True, max_length=9, validators=[django.core.validators.RegexValidator('^|\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='ShipPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairing.ship')),
            ],
            options={
                'unique_together': {('ship', 'timestamp')},
            },
        ),
    ]
