# Generated by Django 3.1.1 on 2020-09-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipposition',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='shipposition',
            old_name='lng',
            new_name='longitude',
        ),
    ]
